### ISSUE TITLE
What is the main difference of this js vs dc.js ?

### ISSUE THREAD

**Issue by hkbeer** [dc-js/dc.graph.js#64]
Would anyone help to tell what are the main differences of this js vs dc.js ?

**Comment by gordonwoodhull** [comment]
Sorry for the lack of introductory material - I've been quiet about this library because it is experimental. It's starting to be useful for general users, though.

This library is for network visualization, i.e. node-link diagrams. It's compatible with dc.js for charts and dc.leaflet.js for maps, thus the name.

For general discussion of this library, please use the dc.js users group.

https://groups.google.com/forum/?fromgroups#!forum/dc-js-user-group
